### ISSUE TITLE
Missing git tag for 1.8.0.27 release

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/go-dbus-factory#23]
go-dbus-factory 1.8.0.27 is found in community edition but there is no such tag here.

**Comment by xmuli** [comment]
Now it's a separate sync tag, but maintenance isn't there yet!

**Comment by felixonmars** [comment]
> Now it's a separate sync tag, but maintenance isn't there yet!

Please make sure the syncing of tags work, at least for published versions present in the community edition. Downstream distributions are now super confused :/

**Comment by justforlxz** [comment]
tag updated.
